/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.farmia.streaming.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** This schema describes an anomalous telemetry temperature event */
@org.apache.avro.specific.AvroGenerated
public class SensorAlert extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -2322173027400183019L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SensorAlert\",\"namespace\":\"com.farmia.streaming.data\",\"doc\":\"This schema describes an anomalous telemetry temperature event\",\"fields\":[{\"name\":\"sensor_id\",\"type\":{\"type\":\"string\",\"arg.properties\":{\"regex\":\"sensor_[1-9]{3}\"}}},{\"name\":\"alert_type\",\"type\":\"string\"},{\"name\":\"timestamp\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\",\"arg.properties\":{\"iteration\":{\"start\":1741511477,\"step\":1}}}},{\"name\":\"details\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<SensorAlert> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SensorAlert> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SensorAlert> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SensorAlert> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SensorAlert> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SensorAlert to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SensorAlert from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SensorAlert instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SensorAlert fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence sensor_id;
  private java.lang.CharSequence alert_type;
  private java.time.Instant timestamp;
  private java.lang.CharSequence details;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SensorAlert() {}

  /**
   * All-args constructor.
   * @param sensor_id The new value for sensor_id
   * @param alert_type The new value for alert_type
   * @param timestamp The new value for timestamp
   * @param details The new value for details
   */
  public SensorAlert(java.lang.CharSequence sensor_id, java.lang.CharSequence alert_type, java.time.Instant timestamp, java.lang.CharSequence details) {
    this.sensor_id = sensor_id;
    this.alert_type = alert_type;
    this.timestamp = timestamp.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
    this.details = details;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sensor_id;
    case 1: return alert_type;
    case 2: return timestamp;
    case 3: return details;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      new org.apache.avro.data.TimeConversions.TimestampMillisConversion(),
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sensor_id = (java.lang.CharSequence)value$; break;
    case 1: alert_type = (java.lang.CharSequence)value$; break;
    case 2: timestamp = (java.time.Instant)value$; break;
    case 3: details = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sensor_id' field.
   * @return The value of the 'sensor_id' field.
   */
  public java.lang.CharSequence getSensorId() {
    return sensor_id;
  }


  /**
   * Sets the value of the 'sensor_id' field.
   * @param value the value to set.
   */
  public void setSensorId(java.lang.CharSequence value) {
    this.sensor_id = value;
  }

  /**
   * Gets the value of the 'alert_type' field.
   * @return The value of the 'alert_type' field.
   */
  public java.lang.CharSequence getAlertType() {
    return alert_type;
  }


  /**
   * Sets the value of the 'alert_type' field.
   * @param value the value to set.
   */
  public void setAlertType(java.lang.CharSequence value) {
    this.alert_type = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public java.time.Instant getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(java.time.Instant value) {
    this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
  }

  /**
   * Gets the value of the 'details' field.
   * @return The value of the 'details' field.
   */
  public java.lang.CharSequence getDetails() {
    return details;
  }


  /**
   * Sets the value of the 'details' field.
   * @param value the value to set.
   */
  public void setDetails(java.lang.CharSequence value) {
    this.details = value;
  }

  /**
   * Creates a new SensorAlert RecordBuilder.
   * @return A new SensorAlert RecordBuilder
   */
  public static com.farmia.streaming.data.SensorAlert.Builder newBuilder() {
    return new com.farmia.streaming.data.SensorAlert.Builder();
  }

  /**
   * Creates a new SensorAlert RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SensorAlert RecordBuilder
   */
  public static com.farmia.streaming.data.SensorAlert.Builder newBuilder(com.farmia.streaming.data.SensorAlert.Builder other) {
    if (other == null) {
      return new com.farmia.streaming.data.SensorAlert.Builder();
    } else {
      return new com.farmia.streaming.data.SensorAlert.Builder(other);
    }
  }

  /**
   * Creates a new SensorAlert RecordBuilder by copying an existing SensorAlert instance.
   * @param other The existing instance to copy.
   * @return A new SensorAlert RecordBuilder
   */
  public static com.farmia.streaming.data.SensorAlert.Builder newBuilder(com.farmia.streaming.data.SensorAlert other) {
    if (other == null) {
      return new com.farmia.streaming.data.SensorAlert.Builder();
    } else {
      return new com.farmia.streaming.data.SensorAlert.Builder(other);
    }
  }

  /**
   * RecordBuilder for SensorAlert instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SensorAlert>
    implements org.apache.avro.data.RecordBuilder<SensorAlert> {

    private java.lang.CharSequence sensor_id;
    private java.lang.CharSequence alert_type;
    private java.time.Instant timestamp;
    private java.lang.CharSequence details;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.farmia.streaming.data.SensorAlert.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[1].schema(), other.alert_type);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.details)) {
        this.details = data().deepCopy(fields()[3].schema(), other.details);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing SensorAlert instance
     * @param other The existing instance to copy.
     */
    private Builder(com.farmia.streaming.data.SensorAlert other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.sensor_id)) {
        this.sensor_id = data().deepCopy(fields()[0].schema(), other.sensor_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.alert_type)) {
        this.alert_type = data().deepCopy(fields()[1].schema(), other.alert_type);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[2].schema(), other.timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.details)) {
        this.details = data().deepCopy(fields()[3].schema(), other.details);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'sensor_id' field.
      * @return The value.
      */
    public java.lang.CharSequence getSensorId() {
      return sensor_id;
    }


    /**
      * Sets the value of the 'sensor_id' field.
      * @param value The value of 'sensor_id'.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder setSensorId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.sensor_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sensor_id' field has been set.
      * @return True if the 'sensor_id' field has been set, false otherwise.
      */
    public boolean hasSensorId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sensor_id' field.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder clearSensorId() {
      sensor_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'alert_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getAlertType() {
      return alert_type;
    }


    /**
      * Sets the value of the 'alert_type' field.
      * @param value The value of 'alert_type'.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder setAlertType(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.alert_type = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'alert_type' field has been set.
      * @return True if the 'alert_type' field has been set, false otherwise.
      */
    public boolean hasAlertType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'alert_type' field.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder clearAlertType() {
      alert_type = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public java.time.Instant getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder setTimestamp(java.time.Instant value) {
      validate(fields()[2], value);
      this.timestamp = value.truncatedTo(java.time.temporal.ChronoUnit.MILLIS);
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder clearTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'details' field.
      * @return The value.
      */
    public java.lang.CharSequence getDetails() {
      return details;
    }


    /**
      * Sets the value of the 'details' field.
      * @param value The value of 'details'.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder setDetails(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.details = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'details' field has been set.
      * @return True if the 'details' field has been set, false otherwise.
      */
    public boolean hasDetails() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'details' field.
      * @return This builder.
      */
    public com.farmia.streaming.data.SensorAlert.Builder clearDetails() {
      details = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SensorAlert build() {
      try {
        SensorAlert record = new SensorAlert();
        record.sensor_id = fieldSetFlags()[0] ? this.sensor_id : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.alert_type = fieldSetFlags()[1] ? this.alert_type : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.timestamp = fieldSetFlags()[2] ? this.timestamp : (java.time.Instant) defaultValue(fields()[2]);
        record.details = fieldSetFlags()[3] ? this.details : (java.lang.CharSequence) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SensorAlert>
    WRITER$ = (org.apache.avro.io.DatumWriter<SensorAlert>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SensorAlert>
    READER$ = (org.apache.avro.io.DatumReader<SensorAlert>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










